CREATE TABLE [dbo].['2018$'] (
    [hotel]                          NVARCHAR (255) NULL,
    [is_canceled]                    FLOAT (53)     NULL,
    [lead_time]                      FLOAT (53)     NULL,
    [arrival_date_year]              FLOAT (53)     NULL,
    [arrival_date_month]             NVARCHAR (255) NULL,
    [arrival_date_week_number]       FLOAT (53)     NULL,
    [arrival_date_day_of_month]      FLOAT (53)     NULL,
    [stays_in_weekend_nights]        FLOAT (53)     NULL,
    [stays_in_week_nights]           FLOAT (53)     NULL,
    [adults]                         FLOAT (53)     NULL,
    [children]                       FLOAT (53)     NULL,
    [babies]                         FLOAT (53)     NULL,
    [meal]                           NVARCHAR (255) NULL,
    [country]                        NVARCHAR (255) NULL,
    [market_segment]                 NVARCHAR (255) NULL,
    [distribution_channel]           NVARCHAR (255) NULL,
    [is_repeated_guest]              FLOAT (53)     NULL,
    [previous_cancellations]         FLOAT (53)     NULL,
    [previous_bookings_not_canceled] FLOAT (53)     NULL,
    [reserved_room_type]             NVARCHAR (255) NULL,
    [assigned_room_type]             NVARCHAR (255) NULL,
    [booking_changes]                FLOAT (53)     NULL,
    [deposit_type]                   NVARCHAR (255) NULL,
    [agent]                          FLOAT (53)     NULL,
    [company]                        NVARCHAR (255) NULL,
    [days_in_waiting_list]           FLOAT (53)     NULL,
    [customer_type]                  NVARCHAR (255) NULL,
    [adr]                            FLOAT (53)     NULL,
    [required_car_parking_spaces]    FLOAT (53)     NULL,
    [total_of_special_requests]      FLOAT (53)     NULL,
    [reservation_status]             NVARCHAR (255) NULL,
    [reservation_status_date]        DATETIME       NULL
);
GO

